  language: "zh"

  # pipeline:
  # - name: "tokenizer_jieba"
  # - name: "bert_vectors_featurizer"
  #   ip: '127.0.0.1'
  #   port: 5555
  #   port_out: 5556
  #   show_server_config: True
  #   timeout: 10000
  # - name: "intent_estimator_classifier_tensorflow_embedding_bert"
  # - name: "nlp_spacy"
  # - name: "ner_crf"


  pipeline:
  - name: "tokenizer_jieba"
  - name: "intent_featurizer_wordvector"
    bert: 'data/chinese_L-12_H-768_A-12'
    bert_type: 'mean'
  
  - name: "intent_classifier_tensorflow_embedding"

  - name: "ner_crf"
  - name: "jieba_pseg_extractor"

  